"""empty message

Revision ID: f0e586119909
Revises: 1.9.2
Create Date: 2023-09-03 10:59:02.524254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0e586119909'
down_revision = '1.9.2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pf_name', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('pf_slug', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=1000), nullable=True))
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('roms', schema=None) as batch_op:
        batch_op.alter_column('p_slug',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('file_name_no_tags',
               existing_type=mysql.VARCHAR(length=450),
               nullable=True)
        batch_op.alter_column('url_screenshots',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('path_screenshots',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roms', schema=None) as batch_op:
        batch_op.alter_column('path_screenshots',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('url_screenshots',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('file_name_no_tags',
               existing_type=mysql.VARCHAR(length=450),
               nullable=False)
        batch_op.alter_column('p_slug',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('logo_url')
        batch_op.drop_column('pf_slug')
        batch_op.drop_column('pf_name')
        batch_op.drop_column('generation')

    # ### end Alembic commands ###
